# Generated by Django 6.1.1 on 2026-10-06 02:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('request_type', models.CharField(choices=[('general', 'General'), ('technical', 'Technical support'), ('access', 'Access'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='users.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblservicerequest',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_updates', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'tblrequestupdate',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'priority'], name='sr_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['requester', 'status'], name='sr_requester_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_to', 'status'], name='sr_assignee_status_idx'),
        ),
    ]
